name = "Simple match all"

[[streams]]
    name = "default"
    description = "All incoming messages"
    pipelines = ["many stages"]

[[streams]]
    name = "unused"
    description = "A stream that never contains messages"
    pipelines = []

